SELECT_SEND_DATA =
SELECT
    MESSAGE_ID,
    KANJI_NAME,
    KANA_NAME,
    MAIL_ADDRESS,
    EXTENSION_NUMBER_BUILDING,
    EXTENSION_NUMBER_PERSONAL,
    STATUS,
    INSERT_USER_ID,
    INSERT_EXECUTION_ID,
    INSERT_REQUEST_ID
FROM
    SEND_MESSAGE_2
WHERE
    STATUS = '0'
ORDER BY
    MESSAGE_ID

UPDATE_NORMAL_END =
UPDATE
    SEND_MESSAGE_2
SET
    STATUS = '1',
    UPDATED_USER_ID = :updatedUserId,
    UPDATED_DATE = :updatedDate
WHERE
    MESSAGE_ID = :messageId

UPDATE_ABNORMAL_END =
UPDATE
    SEND_MESSAGE_2
SET
    STATUS = '9',
    UPDATED_USER_ID = :updatedUserId,
    UPDATED_DATE = :updatedDate
WHERE
    MESSAGE_ID = :messageId

