SELECT_SEND_DATA =
SELECT
    MESSAGE_ID,
    KEI_NO,
    ITEM_CODE_1,
    ITEM_NAME_1,
    ITEM_AMOUNT_1,
    ITEM_CODE_2,
    ITEM_NAME_2,
    ITEM_AMOUNT_2,
    INSERT_USER_ID,
    INSERT_DATE,
    INSERT_EXECUTION_ID,
    INSERT_REQUEST_ID,
    UPDATED_USER_ID,
    UPDATED_DATE
FROM
    SEND_MESSAGE_1
WHERE
    STATUS = '0'
ORDER BY
    MESSAGE_ID

UPDATE_NORMAL_END =
UPDATE
    SEND_MESSAGE_1
SET
    STATUS = '1',
    UPDATED_USER_ID = :updatedUserId,
    UPDATED_DATE = :updatedDate
WHERE
    MESSAGE_ID = :messageId

UPDATE_ABNORMAL_END =
UPDATE
    SEND_MESSAGE_1
SET
    STATUS = '9',
    UPDATED_USER_ID = :updatedUserId,
    UPDATED_DATE = :updatedDate
WHERE
    MESSAGE_ID = :messageId

